### ISSUE TITLE
libcurl issue

### ISSUE THREAD

**Issue by muszar** [macchky/cpuminer#3]
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.47.0
checking for libcurl >= version 7.15.2... yes
checking whether libcurl is usable... no
configure: error: Missing required libcurl >= 7.15.2

the libcurl is already installed:
curl is already the newest version (7.47.0-1ubuntu2.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by macchky** [comment]
Install libcurl4-openssl-dev

Or use prebuild binary
https://github.com/macchky/cpuminer/releases/tag/v2.6.0

**Comment by muszar** [comment]
already installed
root@Ubuntu-1604-xenial-64-minimal ~ # apt-get install libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by macchky** [comment]
Try Reboot or reLogin

**Comment by muszar** [comment]
Same problem even after a reboot of the server:
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.47.0
checking for libcurl >= version 7.15.2... yes
checking whether libcurl is usable... no
configure: error: Missing required libcurl >= 7.15.2

**Comment by macchky** [comment]
re run
./autogen.sh

**Comment by muszar** [comment]
same issue:
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.47.0
checking for libcurl >= version 7.15.2... yes
checking whether libcurl is usable... no
configure: error: Missing required libcurl >= 7.15.2

**Comment by macchky** [comment]
hmm
But It's not cpuminer issue, so google it

**Comment by muszar** [comment]
all was OK with the old version that I deployed on 4 servers. Since the last modification impossible to resolve the issue.

**Comment by macchky** [comment]
git pull!
