### ISSUE TITLE
tell me please --cpu-affinity

### ISSUE THREAD

**Issue by chinahamu** [macchky/cpuminer#4]
1. Celeron Dual-Core B830
2. AMB A10-6700

What kind of setting is desirable　--cpu-affinity

**Comment by macchky** [comment]
cpu-affinity は擬似的にHT or SMTを切るような効果が出るものなので、HT or SMTがついてる場合のみ効果があります。
なので上記のCPUには必要ないです。

-t オプションでコア数分のスレッドを指定するだけで大丈夫です
